### ISSUE TITLE
Can't see what is written inside the share input

### ISSUE THREAD

**Issue by borradaniele** [Fankserver/atom-firepad#12]
After share a file, even if the shearing session start correctly and you can se the shearing stream it' s impossible to see what you' re typing in the session name input.

**Comment by aloncarmel** [comment]
same here. there are alot of deprecated issues. im trying to update this and hopefully post some patch.

**Comment by Fank** [comment]
Is this still an issue?

**Comment by borradaniele** [comment]
Fixed now! Thank you for the support love this plugin!

2015-06-23 0:28 GMT+02:00 Florian Kinder <notifications@github.com>:

> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Fankserver/atom-firepad/issues/12#issuecomment-114286793>
> .
>



-- 
Borra Daniele

**Comment by Fank** [comment]
Help us to improve this plugin by sharing your ideas via issues. :)
