### ISSUE TITLE
Firebase URL should be customizable

### ISSUE THREAD

**Issue by Fank** [Fankserver/atom-firepad#16]
e.g. https://github.com/Fankserver/atom-firepad/blob/dd0c3cb699d322346b94f7b689ba8d5704600bd1/lib/firepad.coffee#L26 which is currently hardcoded.

**Comment by Fank** [comment]
@mikelehen I choose you as contact: Is it possible to host an local Firebase server?

I found the following tutorial how to use [Firebase](https://www.firebase.com/docs/web/guide/understanding-data.html). And maybe some people (like me), sitting behind stupid Proxy server or want use sharing locally, and don't want to use the official/public one.

**Comment by mikelehen** [comment]
@Fank Unfortunately it's not possible.  Firebase is a cloud service and there's no way to install it locally.  You can of course create your own Firebase instances though.  But they'll still be hosted on our servers.

FYI- Firebase should generally work fine behind proxies unless it's exceptionally restricted.  If you're having problems, I'd be curious to know about it.

**Comment by Fank** [comment]
Ah ok, yea currently the atom package doesn't support proxy.
So ill need to focus on this too.
