### ISSUE TITLE
Can't "unshare" unless I close tab/pane

### ISSUE THREAD

**Issue by ryanaltvater** [Fankserver/atom-firepad#20]
Once I "share" a file/session, I can't run the "unshare" command via "cmd + shift + P". Closing the tab/pane is the only method for unsharing, and it throws the notification message below.

<img width="501" alt="screen shot 2015-08-04 at 11 34 07 am" src="https://cloud.githubusercontent.com/assets/1336787/9064915/d00f98e2-3a9c-11e5-95e2-e06e8a4d1aa3.png">

**Comment by Fank** [comment]
Thanks for reporting, its a known issue #4 
Please subscribe to this issue.
I hope the firebase guys will update there repo so we can "fix" unsharing.
