### ISSUE TITLE
Info box covers last line of file and footer bar while sharing

### ISSUE THREAD

**Issue by nicolaiskogheim** [Fankserver/atom-firepad#8]
Atom 0.73.0
Firepad 0.3.1

:sailboat: 

![firepad sharing info box shadows last line when sharing](https://f.cloud.github.com/assets/2117636/2429580/837fa9cc-ac8b-11e3-8992-a31ff1fd9f07.gif)

**Comment by Fank** [comment]
Due the new service API, this view information should be integrated in the status bar.
