### ISSUE TITLE
"This file is shared" shows up on every open file.

### ISSUE THREAD

**Issue by nicolaiskogheim** [Fankserver/atom-firepad#9]
Atom 0.73.0
Firepad 0.3.1

When one file is being shared, one could be led to believe that everything is shared.
Opening new/existing files produces the same issue.

Edit: This is not true when opening a new window.

![this file is shared shows up on every open file](https://f.cloud.github.com/assets/2117636/2429599/d499f6b8-ac8c-11e3-9470-9d60c6705f7f.gif)

**Comment by Fank** [comment]
The current problem is that the pane is shared, but the handling is global. Which does not allow people to host a second pane.

I'll focus on this issue soon, but it will need some rework to handle it pane based.
